version: "2"
volumes:
    db-data:
services:
    web:
        restart: always
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./backend:/backend
            - ./logs/nginx:/logs/nginx
            - ./config/nginx/xdebug:/etc/nginx/xdebug
            - ./config/nginx/hosts:/etc/nginx/hosts
            - ./config/nginx/init.conf:/etc/nginx/conf.d/default.conf
        networks:
            - php-network
    php:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./backend:/backend
            - ./logs/xdebug:/logs/xdebug
            - ./config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
            - ./logs/php-fpm/:/tmp/xdebug_log
        networks:
            - php-network
        environment:
            POSTGRES_DB: "mysite"
            POSTGRES_USER: "mysiteuser"
            POSTGRES_PASSWORD: "mysitepass"
            POSTGRES_DB_HOST: "postgresql"
    composer:
        image: composer
        volumes:
            - ./backend:/app
        command: install
        depends_on:
            - php
    postgresql:
        build:
            context: ./db
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: "mysite"
            POSTGRES_USER: "mysiteuser"
            POSTGRES_PASSWORD: "mysitepass"
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - php-network

    adminer:
        image: adminer
        container_name: nuxt-django-postgresql.adminer
        restart: always
        ports:
            - 8888:8080
        depends_on:
            - postgresql
        networks:
            - php-network
    nuxt:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - 3000:3000
        command: bash -c "npm install && npm run dev"
        networks:
            - php-network
        depends_on:
            - postgresql



networks:
    php-network:
        driver: bridge
